apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common.yaml
  - customer-app.yaml
  - article-app.yaml
  - redpanda.yaml
  - kafka-connect.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: sap-integration
