server:
  port: ${ARTICLE_SERVER_PORT:8082}

spring:
  application:
    name: article-app
  config:
    import: "application-common.yml"
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/poc}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/article}
  elasticsearch:
    uris: ${ES_URL:http://localhost:9200}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: article-consumer
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

article:
  kafka:
    topic: outbox.ARTICLE
    group: article-consumer

sap:
  article:
    s4:
      path: /sap/opu/odata/sap/API_PRODUCT